name: Deploy Portfolio Web

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, nawasena, production]

    steps:
      - name: Deploy VPS
        run: |
          cd ~/apps/portfolio-web/frontend
          git pull
          docker compose down
          docker compose up -d --build
